---
version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - (Get-ECRLoginCommand).Password | docker login --username AWS \
        --password-stdin 032088591384.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building the application...
      - mvn clean package
      - echo Building Docker image...
      - docker build -t my-spring-boot-app .
      - docker tag springbootrepo:latest \
        032088591384.dkr.ecr.us-east-1.amazonaws.com/springbootrepo:latest

  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push 032088591384.dkr.ecr.us-east-1.amazonaws.com/ \
        springbootrepo:latest
      - echo Build completed successfully.

artifacts:
  files:
    - target/*.jar
  discard-paths: true
